### ISSUE TITLE
Support import as ES module type

### ISSUE THREAD

**Issue by bolinocroustibat** [cocopon/tweakpane#209]
It would be great if Tweakpane could support ES module (`type="module"`) import.

**Comment by cocopon** [comment]
It's tough work in several reason:
- [TypeScript support](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/) (TS doesn't support ES module except in beta)
- keeping backward compatibility
- etc... 

For now you can use [Skypack](https://www.skypack.dev/view/tweakpane), the CDN that converts packages into ES modules.

Ref: https://github.com/cocopon/tweakpane/issues/207#issuecomment-803798190

**Comment by FractalHQ** [comment]
This fixes skypack's typescript support:

> You can add typing to a module via declare module. Create .d.ts file with this:
> ```ts
> declare module "https://cdn.skypack.dev/chai" {
>   import chai from "chai";
>   export = chai;
> }
> ```

From: https://github.com/microsoft/TypeScript/issues/46936#issuecomment-981482591

**Comment by ghostdevv** [comment]
ESM Supports importing from esm or cjs so that isn't an issue. Especially when using typescript as there are extra compatibility features. The type issue I found is the lack of `@tweakpane/core` as a dependancy of `tweakpane`

You can easily support multiple distributions for this package, if you expect people to be bundling this then ESM support is also super important as that is the only way to treeshake. You should take a look at tsup to replace the current rollup build step you have

**Comment by cocopon** [comment]
Released in v4.0.0.
