### ISSUE TITLE
Improve events performance

### ISSUE THREAD

**Issue by vlucendo** [cocopon/tweakpane#250]
Hello,

Right now when I have a tweakpane with a few dozen inputs, a lot of move events are being registered affecting pretty significantly to the performance every time I move the mouse:

![image](https://user-images.githubusercontent.com/11018451/113646138-7f46d800-9688-11eb-8627-624665d301ea.png)

I suspect this has to do with the event listeners of the mouse click and drag input. Would it be possible to only bind the `mousedown` and `touchstart` events, add the rest of the events when the user is interacting with that input and remove the events again on `mouseup` / `touchend`? This way I think the performance would be much better.

Cheers!

**Comment by cocopon** [comment]
Thank you for using Tweakpane. Will #227 solve this issue?

**Comment by thscott** [comment]
I think what @vlucendo is getting at is that in the PointerClass, mousemove and mouseup should only be bound on mousedown.

So instead of [pressed flag](https://github.com/cocopon/tweakpane/blob/852cb5de805d45ba46e5b5a8fc3b39d2c77fa674/lib/common/view/pointer-handler.ts#L63), you'd add the document mousemove and mousemove listeners [here](https://github.com/cocopon/tweakpane/blob/852cb5de805d45ba46e5b5a8fc3b39d2c77fa674/lib/common/view/pointer-handler.ts#L105) and remove them both [here](https://github.com/cocopon/tweakpane/blob/852cb5de805d45ba46e5b5a8fc3b39d2c77fa674/lib/common/view/pointer-handler.ts#L134).

As to whether this would improve performance, I've not tested it but seems like it can't do anything but help.

**Comment by cocopon** [comment]
Ah sorry, I hadn't read that well. It should be improved for sure.

**Comment by vlucendo** [comment]
Yes sorry, @thscott explained exactly what I meant.
Right now the performance drop is very noteceiable once you have a big number of inputs (>100). Having such a big number is pretty normal once you start adding folders and creating reusable panels.

Thanks!

**Comment by cocopon** [comment]
Fixed in 2.3.0. Thank you for your help!

**Comment by vlucendo** [comment]
All the performance issues I saw are fixed now, thanks!
