### ISSUE TITLE
dragging support 

### ISSUE THREAD

**Issue by Roxgame95** [cocopon/tweakpane#301]
it will be nice if you add dragging support !!

**Comment by cocopon** [comment]
If you are talking about dragging a pane, it is out of the scope of the library.
Related: #88

**Comment by atlllas** [comment]
Why is it out of the scope of the library? what can be done to enable this

**Comment by cocopon** [comment]
> Why is it out of the scope of the library?

Please refer the related comment:
> Tweakpane has an option container to specify its parent element and users can locate the pane to anywhere with that option. So I think a position of the pane is out of scope of the library.
https://github.com/cocopon/tweakpane/issues/88#issuecomment-692647065

The scope of Tweakpane is as far as specifying a container element. The position and the size of the pane should be handled by CSS since it's a matter of appearance. If you want to implement a draggable pane, you should make a container element draggable.

**Comment by atlllas** [comment]
Makes sense. Thank you for the explanation!

**Comment by kitschpatrol** [comment]
If case anyone else finds this issue and is interested in a draggable Tweakpane, I have an implementation in a Tweakpane x Svelte" wrapper I wrote, [svelte-tweakpane-ui](https://kitschpatrol.com/svelte-tweakpane-ui/docs/features#draggability).

This particular implementation is pretty reliant on Svelte, but [the code](https://github.com/kitschpatrol/svelte-tweakpane-ui/blob/main/src/lib/internal/InternalPaneDraggable.svelte) still might be helpful.
