### ISSUE TITLE
[bug] [feature-request] Respect `step` precision for floats.

### ISSUE THREAD

**Issue by FractalHQ** [cocopon/tweakpane#560]
Hey there!  I've been struggling a bit to prevent TP from converting my floats into huge (slightly off) numbers as it can introduce some bugs and can be cumbersome when dealing with presets.

For example:

```js
	import { Pane } from 'tweakpane'

	const gui = new Pane()

	const params = {
		foo: 1,
		bar: 2,
	}
	
	gui.addInput(params, 'foo', {
		min: 0,
		max: 2,
		step: 0.01,
		format: (v) => v.toFixed(2), // doesn't help
	})
	gui.addInput(params, 'bar', {
		min: 0,
		max: 2,
		step: 0.001,
		format: (v) => v.toFixed(3),  // doesn't help
	})
```

Despite supplying both a step and format option, when I set the inputs to these values:

![Screenshot 2023-07-11 at 4 39 09 PM](https://github.com/cocopon/tweakpane/assets/55504972/d7a28154-60b5-435e-8553-ce1231dcc617)

It actually gives me these values:

```json
{
  "foo": 0.49999999999999994,
  "bar": 1.3699999999999999
}
```

I'm both curious why this happens, and wondering if there should be a way to tell TP to respect the numbers provided?

**Comment by FractalHQ** [comment]
I also noticed that even the number `1` will result in `0.9999999999999999`. Is there a benefit to this behavior?

**Comment by cocopon** [comment]
Thank you for reporting the issue.

This seems to be caused by number precision of JavaScript. Here is the code that constrains a number with step:

https://github.com/cocopon/tweakpane/blob/3d78f6b6c70c396c3fd8d0213aeee9899e1eeded/packages/core/src/common/constraint/step.ts#L15-L19

Let's consider a specific case. For example, suppose the slider knob is dragged and the value becomes `1.1304347826086956`.

- `this.origin` is `0` since it is the same as the min value of the binding
- `this.step` is `0.01` since it is the same as the step value of the binding
- `r` is `113`
- the result of `o + r * this.step` is `1.1300000000000001`

`Number` of JavaScript has double-precision. It means that it has a precision of about 15 digits.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#number_encoding

> I also noticed that even the number 1 will result in 0.9999999999999999. Is there a benefit to this behavior?

It may be occurred because `value` is slightly different from just `1`. If you specify the value `1`  as the text input, The value should be `1`.

<img width="744" alt="image" src="https://github.com/cocopon/tweakpane/assets/602961/1119fa38-7dfc-45de-ac13-0c6ee5a9df5b">


> `format: (v) => v.toFixed(3),  // doesn't help`

`format` affects only for the display text, not for the actual value.

**Comment by cocopon** [comment]
If you really want to avoid errors due to precision, I recommend to use an integer instead of a decimal for the `step`:

```js
pane = new Tweakpane.Pane(); pane.addBinding({foo: 0}, 'foo', {
  min: 0,
  max: 200,
  step: 1,
}).on('change', (ev) => {
  console.log('value', ev.value / 100);
})
```

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
