### ISSUE TITLE
Panel doesn't collapse 

### ISSUE THREAD

**Issue by diramazioni** [cocopon/tweakpane#573]
The pane or folder doesn't collapse when clicked
```
		const pane = new Pane({title: 'control'})
		const panel = pane.addFolder({title: 'folder'})
```

**Comment by cocopon** [comment]
The latest version works fine in the official document:
https://tweakpane.github.io/docs/

Please share your environment (Tweakpane version, web browser, other code, screencasts, etc.) to reproduce the issue.

**Comment by diramazioni** [comment]
Hi, thanks for looking into this.  The version that got downloaded is "tweakpane": "^4.0.1", 
The version present on the doc does work also with my browser (Firefox 117 on Linux Mint) and correctly collapse.
I think this might be related to svelte... 
I've [made a stackblitz svelte example project ](https://stackblitz.com/edit/sveltejs-kit-template-default-xpchia?file=README.md,package.json,src%2Froutes%2F%2Bpage.svelte) where you can see the issue: 
![recorded](https://github.com/cocopon/tweakpane/assets/682046/9031767b-83aa-4276-894b-3ede0b2c5b2a)

**Comment by cocopon** [comment]
I can only see the welcome screen... is it a correct URL?

<img width="1440" alt="image" src="https://github.com/cocopon/tweakpane/assets/602961/11c6eddb-da16-4cc7-ad1a-e990c5d9f87c">

BTW the pane in the screencast seems to be duplicated. Could it be that multiple panes are instanciated and are overlapping?

<img width="235" alt="image" src="https://github.com/cocopon/tweakpane/assets/602961/48ac2290-1ffe-4659-a10d-e56609665ff9">

**Comment by diramazioni** [comment]
Sorry I guess it got reset now it should work [again](https://stackblitz.com/edit/sveltejs-kit-template-default-xpchia?file=src%2Froutes%2F%2Bpage.svelte)

**Comment by cocopon** [comment]
Hmm, it looks fine in my environment:

- macOS 13.4.1
- Firefox latest (117.0.1)
- Google Chrome latest (116.0.5845.179)

https://github.com/cocopon/tweakpane/assets/602961/2978ad09-7905-4cd7-9850-65e659ba9d6b

**Comment by diramazioni** [comment]
Interestingly, I've checked and in Linux works correctly in Chromium but not in Firefox.
![recorded](https://github.com/cocopon/tweakpane/assets/682046/189e87cd-5276-46ab-9dfa-cb089d3220a7)

**Comment by cocopon** [comment]
Interesting. I modified the code a bit, and how about the result of running the page below?

https://stackblitz.com/edit/sveltejs-kit-template-default-h7jpdj?file=src%2Froutes%2F%2Bpage.svelte

If you get a message `pane created: #` multiple times, or see a number greater than 1, it means that the code is executed repeatedly and multiple panes are created. In this case, it's caused by Svelte or StackBlitz, not Tweakpane.

**Comment by diramazioni** [comment]
nope, only one time.
(Firefox 117.0.1 (64 bit))

**Comment by diramazioni** [comment]
I remind you that I wrote "The version present on the doc does work also with my browser" (Firefox)
I don't know if you introduced some breaking changes in the shipped version.
Generally speaking I tend to exclude Svelte in the equation, especially when code is run inside `if (browser) {} ` is client-side related only

**Comment by cocopon** [comment]
> I remind you that I wrote "The version present on the doc does work also with my browser" (Firefox)

Thank you for pointing that out, I missed it.

> I don't know if you introduced some breaking changes in the shipped version.

The code that is used in the document is completely the same as the shipped version.

> Generally speaking I tend to exclude Svelte in the equation

I'm not familiar with Svelte, but the screencast shows that multiple panes are stacked in one location. It may be caused by something in your environment e.g. live-reloading...?

![image](https://github.com/cocopon/tweakpane/assets/602961/14cd127d-a18e-4ae9-9579-7ea9fc666770)

If you can reproduce the issue, can you open the browser inspector and check the DOM structure? In my estimation, the multiple pane will be found on the DOM tree.

**Comment by diramazioni** [comment]
I checked that without using an inside folder, collapsing work (like in the docs that doesn't use a folder)
With the folder inside I do see repeated elements in the DOM

**Comment by cocopon** [comment]
Could you share a screenshot and the entire DOM when the problem occurs? You can copy the code by right clicking `<html>` in DevTools and choosing `Copy -> Outer HTML`.

![image](https://github.com/cocopon/tweakpane/assets/602961/2bf0ac7e-c63c-4024-83e2-948a0dcc4478)

**Comment by diramazioni** [comment]
Dear Hiroki Kokubun, I swaped my branch and run `pnpm i` again, and the problem is suddenly gone, I think this might depends on the live rebuild / caching I don't know.
I close this for now, If I find again the problem I'll let you know.
Thanks again for developing tweakpane and taking seriously bug reports, it's not an easy job I know
