### ISSUE TITLE
Suggestions to improve docs

### ISSUE THREAD

**Issue by tallneil** [cocopon/tweakpane#628]
Some suggestions to improve the [tweakpane docs website](https://tweakpane.github.io/docs/):

* Move `/docs` to `/`. There is nothing in [tweakpane.github.io/](https://tweakpane.github.io/) so it 404s. 
* Add a favicon
* Update year in the footer from 2018 to 2024
* Get a vanity domain such as tweakpane.io or tweakpane.dev (both are available)

**Comment by cocopon** [comment]
Thank you for your suggestion.

> Move `/docs` to `/`.

The current URL structure is based on the repository name. For instance, `github.com/orgname/reponame` results in `orgname.github.io/reponame`. Since Tweakpane organization manages several repositories, `tweakpane.github.io/docs` is appropriate for `tweakpane/docs`.

> Update year in the footer from 2018 to 2024

It shows the original year of publication. (Ref: [Standard Application Help: Publication/Completion](https://www.copyright.gov/eco/help-publication.html))

> Get a vanity domain such as tweakpane.io or tweakpane.dev (both are available)

Acquiring a domain involves ongoing costs, and there is no guarantee of a consistent sponsorship to cover these expenses. This project is currently maintained on a volunteer basis.
